"""
generate_presentation_preview.py

Read-only reporting utility for a GraphRAG index output folder. Does NOT
touch the GraphRAG pipeline or any of its generated Parquet files -- it
only reads them and writes plain CSV/TXT previews into a separate
`presentation_preview/` folder, for pasting into slides or eyeballing
before a meeting.

Safe to re-run after every future indexing run: it always reads fresh
from --input-dir and overwrites only its own files inside
--output-dir, never anything under data/graphrag_index/.

Run with (from the project root, venv activated):

    python -m scripts.generate_presentation_preview

or with custom paths, e.g. to preview a future full-corpus run instead
of the 7/32-document pilot:

    python -m scripts.generate_presentation_preview \\
        --input-dir data/graphrag_index/full_run/output \\
        --output-dir presentation_preview_full
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# The six GraphRAG output tables we care about for a presentation, in the
# order they're most natural to walk through: what was found (entities,
# relationships), how it was grouped (communities, community_reports),
# then the raw inputs behind it all (documents, text_units).
TABLE_NAMES = [
    "entities",
    "relationships",
    "communities",
    "community_reports",
    "documents",
    "text_units",
]

PREVIEW_ROWS = 20  # rows printed to the terminal
CSV_ROWS = 50  # rows saved to each *_preview.csv

pd.set_option("display.width", 160)
pd.set_option("display.max_columns", 20)


def load_table(input_dir: Path, name: str) -> pd.DataFrame | None:
    """Read one GraphRAG output Parquet file. Returns None (with a
    printed warning) if the file doesn't exist, so one missing table
    (e.g. an interrupted run with no community_reports.parquet yet)
    doesn't crash the whole preview."""
    path = input_dir / f"{name}.parquet"
    if not path.exists():
        print(f"  [skip] {path} not found")
        return None
    return pd.read_parquet(path)


def print_table_summary(name: str, df: pd.DataFrame) -> None:
    print(f"\n{'=' * 78}\n{name.upper()}  ({len(df):,} rows, {len(df.columns)} columns)\n{'=' * 78}")
    print(f"Columns: {list(df.columns)}\n")
    preview = df.head(PREVIEW_ROWS).copy()
    # Long free-text columns (entity/relationship descriptions, community
    # report full_content, etc.) blow out terminal width -- truncate just
    # for the printed view. The saved CSV keeps the full, untruncated text.
    for col in preview.columns:
        if preview[col].dtype == object:
            preview[col] = preview[col].apply(
                lambda v: (v[:70] + "...") if isinstance(v, str) and len(v) > 70 else v
            )
    with pd.option_context("display.max_colwidth", 73):
        print(preview.to_string(index=False))


def save_csv_preview(output_dir: Path, name: str, df: pd.DataFrame) -> Path:
    out_path = output_dir / f"{name}_preview.csv"
    df.head(CSV_ROWS).to_csv(out_path, index=False)
    return out_path


def relationship_type_distribution(df: pd.DataFrame) -> pd.Series:
    """relationships.parquet has no dedicated 'type' column -- the edge
    type (OF_METRIC, OBSERVED_IN, EVIDENCED_BY, ...) is embedded as a
    leading "TYPE: rest of sentence" prefix inside `description`
    (see docs/GRAPHRAG_ENTITY_RELATIONSHIP_SCHEMA.md section 2). Parse
    it out on a best-effort basis; anything that doesn't match the
    pattern is bucketed as "(unlabeled)" rather than dropped."""
    if "description" not in df.columns:
        return pd.Series(dtype=int)

    def extract_type(desc: object) -> str:
        if not isinstance(desc, str):
            return "(unlabeled)"
        match = re.match(r"^([A-Z_]{3,40}):", desc.strip())
        return match.group(1) if match else "(unlabeled)"

    return df["description"].apply(extract_type).value_counts()


def build_summary(tables: dict[str, pd.DataFrame], output_dir: Path) -> str:
    lines: list[str] = []

    def add(line: str = "") -> None:
        lines.append(line)

    add("GraphRAG Pilot Output -- Presentation Summary")
    add("=" * 50)
    add(f"Generated by: scripts/generate_presentation_preview.py")
    add(f"Generated at: {pd.Timestamp.now().isoformat(timespec='seconds')}")
    add("")

    add("Table row counts")
    add("-" * 50)
    for name in TABLE_NAMES:
        if name in tables:
            add(f"  {name:<20} {len(tables[name]):>10,} rows")
        else:
            add(f"  {name:<20} {'(missing)':>10}")
    add("")

    if "entities" in tables:
        entities = tables["entities"]
        add("Entity type distribution")
        add("-" * 50)
        if "type" in entities.columns:
            for etype, count in entities["type"].value_counts().items():
                add(f"  {etype:<20} {count:>10,}")
        else:
            add("  (no 'type' column found in entities.parquet)")
        add(f"  {'TOTAL':<20} {len(entities):>10,}")
        add("")

    if "relationships" in tables:
        relationships = tables["relationships"]
        add("Relationship type distribution (parsed from description prefix)")
        add("-" * 50)
        dist = relationship_type_distribution(relationships)
        for rtype, count in dist.items():
            add(f"  {rtype:<20} {count:>10,}")
        add(f"  {'TOTAL':<20} {len(relationships):>10,}")
        add("")

    if "communities" in tables:
        communities = tables["communities"]
        add("Community level distribution")
        add("-" * 50)
        if "level" in communities.columns:
            for level, count in communities["level"].value_counts().sort_index().items():
                add(f"  level {level:<14} {count:>10,}")
        add(f"  {'TOTAL':<20} {len(communities):>10,}")
        add("")

    if "community_reports" in tables:
        reports = tables["community_reports"]
        add("Community report stats")
        add("-" * 50)
        add(f"  reports generated    {len(reports):>10,}")
        if "rank" in reports.columns:
            add(f"  avg rank             {reports['rank'].mean():>10.2f}")
        if "full_content" in reports.columns:
            avg_len = reports["full_content"].dropna().str.len().mean()
            add(f"  avg report length    {avg_len:>10,.0f} chars")
        add("")

    if "documents" in tables:
        documents = tables["documents"]
        add("Documents indexed")
        add("-" * 50)
        add(f"  documents            {len(documents):>10,}")
        if "title" in documents.columns:
            add(f"  sample titles        {', '.join(documents['title'].head(3).astype(str))}")
        add("")

    if "text_units" in tables:
        text_units = tables["text_units"]
        add("Text unit (chunk) stats")
        add("-" * 50)
        add(f"  text units           {len(text_units):>10,}")
        if "n_tokens" in text_units.columns:
            add(f"  total tokens chunked {text_units['n_tokens'].sum():>10,}")
            add(f"  avg tokens/unit      {text_units['n_tokens'].mean():>10,.1f}")
        add("")

    add("Files written")
    add("-" * 50)
    for name in TABLE_NAMES:
        if name in tables:
            add(f"  {output_dir.name}/{name}_preview.csv")
    add(f"  {output_dir.name}/summary.txt  (this file)")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=PROJECT_ROOT / "data" / "graphrag_index" / "pilot_run" / "output",
        help="Folder containing the GraphRAG *.parquet output files (default: the pilot run's output/).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "presentation_preview",
        help="Folder to write *_preview.csv and summary.txt into (created if missing).",
    )
    args = parser.parse_args()

    input_dir: Path = args.input_dir
    output_dir: Path = args.output_dir

    if not input_dir.exists():
        raise SystemExit(f"Input directory does not exist: {input_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading GraphRAG output from: {input_dir}")
    print(f"Writing preview files to:     {output_dir}\n")

    tables: dict[str, pd.DataFrame] = {}
    for name in TABLE_NAMES:
        df = load_table(input_dir, name)
        if df is None:
            continue
        tables[name] = df
        print_table_summary(name, df)
        csv_path = save_csv_preview(output_dir, name, df)
        print(f"\n  -> saved first {min(CSV_ROWS, len(df))} rows to {csv_path}")

    summary_text = build_summary(tables, output_dir)
    summary_path = output_dir / "summary.txt"
    summary_path.write_text(summary_text)

    print(f"\n{'=' * 78}")
    print(f"Wrote summary to {summary_path}")
    print(f"{'=' * 78}\n")
    print(summary_text)


if __name__ == "__main__":
    main()
